# ExtraSkills by TotomInc
# Question, need support? Feel free to join the official Discord server.
# https://discord.gg/wxWmRCQ2M8

# All messages are supporting MiniMessage format, please see their official documentation:
# https://docs.adventure.kyori.net/minimessage#format

# Determine how to show visual feedback about a skill progression to the player.
# You have multiple ways to give visual feedback such as:
#   - Action-bar: a small text above the player hot-bar
#   - Boss-bar: a progression bar with a custom text
skill-progression:
  action-bar:
    enabled: true
    format: "<#ff7675>{skill_name} <#dfe6e9><bold>»</bold> <#fab1a0>{current_exp}/{exp_required} <bold><#fab1a0>{exp_percentage}%</bold>"
  boss-bar:
    enabled: true
    # Segments to display on the boss-bar, possible values are:
    # NOTCHED_20, NOTCHED_12, NOTCHED_10, NOTCHED_6, PROGRESS
    segments: "NOTCHED_20"
    # Color to use for the boss-bar, possible values are:
    # PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
    color: "PURPLE"
    format: "<#ff7675>{skill_name} <#dfe6e9><bold>»</bold> <#fab1a0>{current_exp}/{exp_required}"
    # A value in seconds that will be used to remove the boss-bar from the
    # player interface.
    remove-after: 3

# Visual feedback when a player level-up a skill. You have multiple ways to
# give visual feedback such as:
#   - Sound: a sound that will be played on the player
#   - Chat: a special message that will only appear to the player
#   - Broadcast: a message sent to all online players of the server
skill-level-up:
  sound:
    enabled: true
    # Name of the sound, see this for a list of possible values:
    # https://www.andre601.ch/Spigot-Sounds/
    name: "ENTITY_PLAYER_LEVELUP"
    # Value between 0 and 1, alter the sound volume.
    volume: 0.75
    # Value between 0.5 and 2, will alter the pitch of the sound.
    pitch: 1
  chat:
    enabled: true
    format: "<#ff7675>Congratulations, you are now <#dfe6e9><bold>level {level}</bold><#ff7675> in <#fab1a0>{skill_name}<#ff7675>!"
  broadcast:
    enabled: true
    # When reaching one of those specific levels, send a broadcast message.
    levels: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950, 975, 990, 1000]
    format: "<#dfe6e9>{player_name} <#ff7675>has reached <#dfe6e9><bold>level {level}</bold> <#ff7675>in <#fab1a0>{skill_name}<#ff7675>!"