# General configuration.
#
# Colors from FlatUIColors (Aussie palette): https://flatuicolors.com/palette/au
# MiniMessage format preview: https://webui.adventure.kyori.net/

action_bar:
  # If true, action-bar is globally enabled.
  enabled: true
  # If true, action-bar is enabled for the "skill experience gained" event.
  enable_for_skill_experience_gained: true
  # If true, action-bar is not sent when player reaches the max skill level.
  disable_on_max_level: true
  # Action-bar message format for the "skill experience gained" event.
  #
  # Valid placeholder values are:
  #   {reward}: experience amount gained in this event.
  #   {skill}: name of the skill, the name is formatted like "Example Skill".
  #   {skill_capitalize}: name of the skill, the name is formatted all in uppercase letters like "EXAMPLE SKILL".
  #   {skill_lowercase}: name of the skill, the name is formatted all in lowercase letter like "example skill".
  #   {experience}: current amount of experience for this skill. Experience amount is formatted without decimals.
  #   {experience_2f}: current amount of experience for this skill. Experience amount is formatted with 2 decimals.
  #   {experience_required}: amount of experience required for level-up. Experience amount is formatted without decimals.
  #   {experience_required_2f}: amount of experience required for level-up. Experience amount is formatted with 2 decimals.
  #   {level}: current player skill level.
  #   {player_name}: name of the player.
  skill_experience_gained_format: "<#f0932b>+{reward} <#ffbe76>{skill_lowercase} experience <#f6e58d>({experience_2f}/{experience_required})"
  # Action-bar message format when a player has reached the max skill level.
  skill_max_level_format: "<#ffbe76>{skill} <#f6e58d>skill maxed"

boss_bar:
  # If true, boss-bar is globally enabled.
  enabled: true
  # If true, boss-bar is not sent when player reaches the max skill level.
  disable_on_max_level: false
  # Type of the boss-bar, can be: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20.
  type: PROGRESS
  # Color of the boss-bar, can be: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
  color: PURPLE
  # Time in seconds before the boss-bar disappear.
  display_time: 2
  # If true, a boss-bar is displayed for the "skill experience gained" event.
  enable_for_skill_experience_gained: true
  # Boss-bar message format for the "skill experience gained" event.
  # Please check documentation for possible placeholder values.
  skill_experience_gained_format: "<#f0932b>{skill} <#ffbe76>{experience_2f}/{experience_required} <#ffbe76>(lvl. {level})"
  # Boss-bar message format when a player has reached the max skill level.
  skill_max_level_format: "<#f0932b>{skill} <#ffbe76>skill maxed <#ffbe76>(lvl. {level})"

title:
  # If true, titles are globally enabled.
  enabled: true
  # If true, send a title for the "skill level-up" event.
  enable_for_skill_level_up: true
  # Title for the "skill level-up" event.
  # Please check documentation for possible placeholder values.
  skill_level_up_title: "<bold><#f0932b>Level-up!"
  # Description for the "skill level-up" event.
  # Please check documentation for possible placeholder values.
  skill_level_up_description: "<bold><#f6e58d>{skill} <#ffbe76>skill is now level <#f0932b>{level}<#ffbe76>!"

sound:
  # If true, sounds are globally enabled.
  enabled: true
  # If true, send a sound for the "skill level-up" event.
  enabled_for_skill_level_up: true
  # ID of the sound, a list of possible values can be found here: https://www.digminecraft.com/lists/sound_list_pc.php
  skill_level_up_sound: entity.player.levelup
  # Category sound chanel option to play the sound to.
  # It's recommended to not change this setting and to leave it to MASTER.
  # Possible values are: MASTER, MUSIC, RECORD, WEATHER, BLOCK, HOSTILE, NEUTRAL, PLAYER, AMBIENT, VOICE.
  skill_level_up_sound_source: MASTER
  # Pitch of the sound, should be a decimal value between 0 and 2.
  skill_level_up_pitch: 0
  # Volume of the sound, should be a decimal value between 0 and 1.
  skill_level_up_volume: 1

# Additional, special properties for abilities.
abilities:
  # Customize configuration for the potion effect applied to the player.
  haster:
    # 1 second = 20 ticks.
    duration_in_ticks: 60
    # Possible values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
    potion_effect: FAST_DIGGING
    # Potion effect amplifier.
    amplifier: 2

# List of game-modes where the plugin should not be enabled. Skill and abilities won't work
# while the player is in one of these game-modes.
disabled_gamemodes:
  - CREATIVE
  - ADVENTURE
  - SPECTATOR

# List of worlds where the plugin should not be enabled. Skills and abilities won't work
# in these worlds.
disabled_worlds:
  - example_world

# If true, gain money on skill level-up. Requires Vault.
enable_gain_money_on_skill_levelup: false
# Formula that will be used to gain money on skill level-up, if "gain_money_on_skill_levelup" is set to true.
money_skill_levelup_expression: "level * 50"

# If true, plugin will check if a block has been placed by a player, which once mined
# won't give skill experience.
check_player_block_placed: true

# If true, use the "global_experience_expression" formula for all skills experience required.
# If set to false, the "experience_expression" of each skill inside "skills.yml" will be used instead.
# This allows you to define a unique experience required formula for each separate skill.
use_global_experience_expression: true
# Formula that will calculate experience required for all skills, if "use_global_experience_expression" is set to true.
global_experience_expression: "IF(level == 1, 100, 100 * level * 1.33)"

# Please, do not touch. Used for plugin configuration versioning.
config_version: 1