# ExtraSkills by TotomInc
# Question, need support? Feel free to join the official Discord server.
# https://discord.gg/wxWmRCQ2M8

# Determine how to show visual feedback about a skill progression to the player.
# You have multiple ways to give visual feedback such as:
#   - Action-bar: a small text above the player hot-bar
#   - Boss-bar: a progression bar with a custom text
#   - Sound: a sound to play on a skill levelup.
skill-progression:
  action-bar:
    enabled: true
    format: "<#ff7675>{skill_name} <#dfe6e9><bold>»</bold> <#fab1a0>{current_exp}/{exp_required} <bold><#fab1a0>{exp_percentage}%</bold>"
