# ExtraSkills by TotomInc
# Question, need support? Feel free to join the official Discord server.
# https://discord.gg/wxWmRCQ2M8

# Determine how to show visual feedback about a skill progression to the player.
# You have multiple ways to give visual feedback such as:
#   - Action-bar: a small text above the player hot-bar
#   - Sound: a sound to play on a skill levelup.
#   - Boss-bar: a progression bar with a custom text
skill-progression:
  # Small text displayed above the player inventory/hot-bar every time he does
  # a skill-related action.
  action-bar:
    enabled: true
    format: "<#ff7675>{skill_name} <#dfe6e9><bold>»</bold> <#fab1a0>{current_exp}/{exp_required} <bold><#fab1a0>{exp_percentage}%</bold>"
  # Sound played only when a player levelup a skill.
  sound:
    enabled: true
    # Name of the sound, see this for a list of possible values:
    # https://www.andre601.ch/Spigot-Sounds/
    name: "ENTITY_PLAYER_LEVELUP"
    # Value between 0 and 1, alter the sound volume.
    volume: 0.75
    # Value between 0.5 and 2, will alter the pitch of the sound.
    pitch: 1
  boss-bar:
    enabled: true
    # Segments to display on the boss-bar, possible values are:
    # NOTCHED_20, NOTCHED_12, NOTCHED_10, NOTCHED_6, PROGRESS
    segments: "NOTCHED_20"
    # Color to use for the boss-bar, possible values are:
    # PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
    color: "PURPLE"
    format: "<#ff7675>{skill_name} <#dfe6e9><bold>»</bold> <#fab1a0>{current_exp}/{exp_required}"
    # A value in seconds that will be used to remove the boss-bar from the
    # player interface.
    remove-after: 3
