name: ExtraSkills
main: io.totominc.ExtraSkills.ExtraSkills
description: Add skills and level-up passives to make your survival server grindier like an RPG.

version: 0.0.1
api-version: 1.18
softdepend: []

author: TotomInc <cazade.thomas@gmail.com>
website: https://totominc.io/

commands:
  esreload:
    description: Reload ExtraSkills plugin.
    usage: /esreload
    permission: extraskills.reload

permissions:
  extraskills.reload:
    description: Allow the user to reload the ExtraSkills plugin.
    default: op
  extraskills.*:
    description: Give all permissions of the ExtraSkills plugin.
    default: op
