name: ExtraSkills
main: io.totominc.extraskills.ExtraSkills
description: Level-up skills such as mining or fishing to gain vanilla-friendly passives.

version: 0.0.1
api-version: 1.19
softdepend: [Vault]

author: TotomInc <cazade.thomas@gmail.com>
website: https://totominc.io/

commands:
  esreload:
    description: Reload ExtraSkills plugin.
    usage: /esreload
    permission: extraskills.reload

permissions:
  extraskills.reload:
    description: Allow the user to reload the ExtraSkills plugin.
    default: op
  extraskills.*:
    description: Give all permissions of the ExtraSkills plugin.
    default: op
